# Generated by Django 5.2.4 on 2025-07-08 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the job position.', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the job role and responsibilities.')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities of the role.', null=True)),
                ('requirements', models.TextField(blank=True, help_text='Required qualifications and skills.', null=True)),
                ('location', models.CharField(blank=True, help_text='Job location (e.g., City, Country).', max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, help_text='Type of employment (e.g., Full-time, Part-time, Contract).', max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, help_text="Salary range for the position (e.g., '$50,000 - $70,000').", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the job was made public.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft'), ('on_hold', 'On Hold')], default='draft', help_text='Current status of the job posting.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the job posting is visible to candidates.')),
                ('posted_by', models.ForeignKey(help_text='The user who posted this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-published_date', 'title'],
            },
        ),
    ]
