# Generated by Django 5.0.14 on 2025-07-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text="AI-generated feedback on the resume's strengths and weaknesses.", null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_resume_score',
            field=models.FloatField(blank=True, help_text='AI-generated score indicating resume match quality against a job.', null=True),
        ),
    ]
